window.MacroDockFoods = [
  {
    name: "Apple",
    servingLabel: "1 medium apple",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    fiber: 4.4,
    sodium: 2,
    calcium: 11,
    iron: 0.2,
    vitaminC: 8,
    potassium: 195
  },
  {
    name: "Banana",
    servingLabel: "1 medium banana",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    fiber: 3.1,
    sodium: 1,
    calcium: 6,
    iron: 0.3,
    vitaminC: 10,
    potassium: 422
  },
  {
    name: "Large egg",
    servingLabel: "1 large egg",
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 4.8,
    fiber: 0,
    sodium: 71,
    calcium: 28,
    iron: 0.9,
    vitaminC: 0,
    potassium: 69
  },
  {
    name: "Bacon, cooked",
    servingLabel: "1 slice",
    calories: 43,
    protein: 3,
    carbs: 0.1,
    fat: 3.3,
    fiber: 0,
    sodium: 137,
    calcium: 1,
    iron: 0.1,
    vitaminC: 0,
    potassium: 45
  },
  {
    name: "Oatmeal, cooked",
    servingLabel: "1 cup cooked",
    calories: 154,
    protein: 6,
    carbs: 27,
    fat: 3,
    fiber: 4,
    sodium: 9,
    calcium: 21,
    iron: 1.7,
    vitaminC: 0,
    potassium: 164
  },
  {
    name: "Whole wheat toast",
    servingLabel: "1 slice",
    calories: 81,
    protein: 4,
    carbs: 14,
    fat: 1.1,
    fiber: 2,
    sodium: 144,
    calcium: 38,
    iron: 1,
    vitaminC: 0,
    potassium: 69
  },
  {
    name: "Milk, 2%",
    servingLabel: "1 cup",
    calories: 122,
    protein: 8,
    carbs: 12,
    fat: 5,
    fiber: 0,
    sodium: 115,
    calcium: 309,
    iron: 0,
    vitaminC: 0,
    potassium: 390
  },
  {
    name: "Chicken breast, cooked",
    servingLabel: "100g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sodium: 74,
    calcium: 15,
    iron: 1,
    vitaminC: 0,
    potassium: 256
  },
  {
    name: "White rice, cooked",
    servingLabel: "1 cup cooked",
    calories: 205,
    protein: 4.3,
    carbs: 45,
    fat: 0.4,
    fiber: 0.6,
    sodium: 2,
    calcium: 16,
    iron: 1.9,
    vitaminC: 0,
    potassium: 55
  },
  {
    name: "Peanut butter",
    servingLabel: "2 tbsp",
    calories: 190,
    protein: 7,
    carbs: 7,
    fat: 16,
    fiber: 2,
    sodium: 140,
    calcium: 17,
    iron: 0.6,
    vitaminC: 0,
    potassium: 189
  },
  {
    name: "Quest Protein Bar, Chocolate Chip Cookie Dough",
    servingLabel: "1 bar",
    calories: 190,
    protein: 21,
    carbs: 21,
    fat: 8,
    fiber: 14,
    sodium: 340,
    calcium: 150,
    iron: 1.1,
    vitaminC: 0,
    potassium: 120
  },
  {
    name: "Clif Bar, Chocolate Chip",
    servingLabel: "1 bar",
    calories: 250,
    protein: 10,
    carbs: 43,
    fat: 5,
    fiber: 4,
    sodium: 180,
    calcium: 45,
    iron: 2,
    vitaminC: 0,
    potassium: 240
  },
  {
    name: "RXBAR, Chocolate Sea Salt",
    servingLabel: "1 bar",
    calories: 210,
    protein: 12,
    carbs: 24,
    fat: 9,
    fiber: 5,
    sodium: 260,
    calcium: 50,
    iron: 2,
    vitaminC: 0,
    potassium: 300
  },
  {
    name: "Apple and almonds",
    servingLabel: "1 snack pack",
    calories: 240,
    protein: 7,
    carbs: 28,
    fat: 14,
    fiber: 8,
    sodium: 2,
    calcium: 90,
    iron: 1.1,
    vitaminC: 8,
    potassium: 310
  },
  {
    name: "Tuna, canned in water",
    servingLabel: "100g",
    calories: 116,
    protein: 25.5,
    carbs: 0,
    fat: 0.8,
    fiber: 0,
    sodium: 338,
    calcium: 11,
    iron: 1,
    vitaminC: 0,
    potassium: 237
  },
  {
    name: "Kiwi",
    servingLabel: "1 medium kiwi",
    calories: 42,
    protein: 0.8,
    carbs: 10,
    fat: 0.4,
    fiber: 2.1,
    sodium: 2,
    calcium: 23,
    iron: 0.2,
    vitaminC: 64,
    potassium: 215
  },
  {
    name: "BioSteel Protein Shake, Chocolate Milkshake",
    servingLabel: "1 bottle",
    calories: 140,
    protein: 30,
    carbs: 4,
    fat: 1,
    fiber: 2,
    sodium: 260,
    calcium: 660,
    iron: 1.4,
    vitaminC: 0,
    potassium: 290
  }
];
